# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 02:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='SPY', max_length=10)),
                ('average_cost', models.FloatField(default=-1)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('market_value', models.FloatField(default=-1)),
                ('quantity', models.IntegerField(default=0)),
                ('volatility', models.FloatField(default=-1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('market_value',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='SPY', max_length=10)),
                ('price', models.FloatField(default=-1)),
                ('volatility', models.FloatField(default=-1)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
