# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='spy', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=-1)),
                ('data_type', models.CharField(default='adjClose', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
