# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='SPY', max_length=10),
        ),
    ]
