# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_remove_stock_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volatility',
            field=models.FloatField(default=-1),
        ),
    ]
